<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('compras')->insert([
        'serial'            => 'ALES05X075BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'ALMOHADAS ',
        'caracteristicas'            => 'ESTANDAR ',
        'ancho'            => '0.50 ',
        'largo'            => '0.75 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'ALPE03X05BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'ALMOHADAS ',
        'caracteristicas'            => 'PEDIATRICA ',
        'ancho'            => '0.30 ',
        'largo'            => '0.50 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'BAAN15X13AZAN ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'BATAS ',
        'caracteristicas'            => 'ANTIFLUIDO AZUL ',
        'ancho'            => '1.50 ',
        'largo'            => '1.30 ',
        'color'            => 'AZUL OSCURA ',
        'tela'            => 'ANTIFLUIDO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'BAAN15X1BLAN ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'BATAS ',
        'caracteristicas'            => 'ANTIFLUIDO BLANCA ',
        'ancho'            => '1.50 ',
        'largo'            => '1.00 ',
        'color'            => 'BLANCO ',
        'tela'            => 'ANTIFLUIDO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'BABL16X12BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'BATAS ',
        'caracteristicas'            => 'BLANCA MANGA LARGA ',
        'ancho'            => '1.60 ',
        'largo'            => '1.20 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'BABL15X11BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'BATAS ',
        'caracteristicas'            => 'BLANCA MANGA CORTA ',
        'ancho'            => '.,50',
        'largo'            => '.,10 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'BAIN12X09BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'BATAS ',
        'caracteristicas'            => 'INFANTIL ',
        'ancho'            => '1.20 ',
        'largo'            => '0.90 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'BAQU16X13VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'BATAS ',
        'caracteristicas'            => 'QUIRURGICA ',
        'ancho'            => '1.60 ',
        'largo'            => '1.30 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CAAB18X2VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'ABIERTO GRANDE ',
        'ancho'            => '1.80 ',
        'largo'            => '2.00 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CADE18X2VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'DE OJO GRANDE ',
        'ancho'            => '1.80 ',
        'largo'            => '2.00 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CADE09X09VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'DE OJO PEQUEÑO ',
        'ancho'            => '0.90 ',
        'largo'            => '0.90 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CADE09X09VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'DE PIEL ',
        'ancho'            => '0.90 ',
        'largo'            => '0.90 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CADE05X05BEDR ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'DE OJO DE URGENCIAS ',
        'ancho'            => '0.50 ',
        'largo'            => '0.50 ',
        'color'            => 'BEIGE ',
        'tela'            => 'DRILAN ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CAEM12X12VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'EMPACAR REMISIAN ',
        'ancho'            => '1.20 ',
        'largo'            => '1.20 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CAFE18X2VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'FENESTRADO ',
        'ancho'            => '1.80 ',
        'largo'            => '2.00 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CALI18X2VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'LISO GRANDE ',
        'ancho'            => '1.80 ',
        'largo'            => '2.00 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CALI05X05BEDR ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'LISO PEQUEÑO ',
        'ancho'            => '0.50 ',
        'largo'            => '0.50 ',
        'color'            => 'BEIGE ',
        'tela'            => 'DRILAN ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CAME18X2VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAMPOS ',
        'caracteristicas'            => 'MEDIA LUNA ',
        'ancho'            => '1.80 ',
        'largo'            => '2.00 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CAGR2X2GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAPSULAS ',
        'caracteristicas'            => 'GRANDE ',
        'ancho'            => '2.00 ',
        'largo'            => '2.00 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CAPE16X15GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAPSULAS ',
        'caracteristicas'            => 'PEDIATRICA GRANDE ',
        'ancho'            => '1.60 ',
        'largo'            => '1.50 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CAPE14X15GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAPSULAS ',
        'caracteristicas'            => 'PEDIATRICA MEDIANA ',
        'ancho'            => '1.40 ',
        'largo'            => '1.50 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'CAPE09X08GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'CAPSULAS ',
        'caracteristicas'            => 'PEDIATRCA PEQUEÑA ',
        'ancho'            => '0.90 ',
        'largo'            => '0.80 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'COCO15X1ESPI ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'COBIJAS ',
        'caracteristicas'            => 'COBERTOR (NEONATOS) ',
        'ancho'            => '1.50 ',
        'largo'            => '1.00 ',
        'color'            => 'ESTAMPADO ',
        'tela'            => 'PIEL CONEJO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'COCO08X09AZPI ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'COBIJAS ',
        'caracteristicas'            => 'COBERTOR (TERAPIA FISICA) ',
        'ancho'            => '0.80 ',
        'largo'            => '0.90 ',
        'color'            => 'AZUL REY ',
        'tela'            => 'PIEL CONEJO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'COES15X22AZPI ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'COBIJAS ',
        'caracteristicas'            => 'ESTANDAR ',
        'ancho'            => '1.50 ',
        'largo'            => '2.20 ',
        'color'            => 'AZUL REY ',
        'tela'            => 'PIEL CONEJO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'COPE12X15ESPI ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'COBIJAS ',
        'caracteristicas'            => 'PEDIATRICA ',
        'ancho'            => '1.20 ',
        'largo'            => '1.50 ',
        'color'            => 'ESTAMPADO ',
        'tela'            => 'PIEL CONEJO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'COCO045X05BLGA ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'COMPRESAS ',
        'caracteristicas'            => 'COMPRESAS ',
        'ancho'            => '0.45 ',
        'largo'            => '0.50 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GAZA ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'COCO18X075BEDR ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'COMPRESEROS ',
        'caracteristicas'            => 'COMPRESEROS ',
        'ancho'            => '1.80 ',
        'largo'            => '0.75 ',
        'color'            => 'BEIGE ',
        'tela'            => 'DRILAN ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FATA07X05AZAL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FAJAS ',
        'caracteristicas'            => 'TALLA S ',
        'ancho'            => '0.70 ',
        'largo'            => '0.50 ',
        'color'            => 'AZUL ',
        'tela'            => 'ALGODAN LICRADO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FATA074X055VEAL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FAJAS ',
        'caracteristicas'            => 'TALLA M ',
        'ancho'            => '0.74 ',
        'largo'            => '0.55 ',
        'color'            => 'VERDE ',
        'tela'            => 'ALGODAN LICRADO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FATA076X06ROAL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FAJAS ',
        'caracteristicas'            => 'TALLA L ',
        'ancho'            => '0.76 ',
        'largo'            => '0.60 ',
        'color'            => 'ROSADO ',
        'tela'            => 'ALGODAN LICRADO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FATA084X06AZAL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FAJAS ',
        'caracteristicas'            => 'TALLA XL ',
        'ancho'            => '0.84 ',
        'largo'            => '0.60 ',
        'color'            => 'AZUL REY ',
        'tela'            => 'ALGODAN LICRADO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FATA09X06VEAL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FAJAS ',
        'caracteristicas'            => 'TALLA XXL ',
        'ancho'            => '0.90 ',
        'largo'            => '0.60 ',
        'color'            => 'VERDE ',
        'tela'            => 'ALGODAN LICRADO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FOCA039X056GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FORROS ',
        'caracteristicas'            => 'CABAS ',
        'ancho'            => '0.39 ',
        'largo'            => '0.56 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FOEL05X1GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FORROS ',
        'caracteristicas'            => 'ELECTRO ',
        'ancho'            => '0.50 ',
        'largo'            => '1.00 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FOLA15X06GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FORROS ',
        'caracteristicas'            => 'LAMPARA ',
        'ancho'            => '1.50 ',
        'largo'            => '0.60 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FOPO05X06GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FORROS ',
        'caracteristicas'            => 'PORTA BRAZO ',
        'ancho'            => '0.50 ',
        'largo'            => '0.60 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FUDE06X1VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FUNDAS ',
        'caracteristicas'            => 'DE MAYO ',
        'ancho'            => '0.60 ',
        'largo'            => '1.00 ',
        'color'            => 'VERDE ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FUES05X07BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FUNDAS ',
        'caracteristicas'            => 'ESTANDAR ',
        'ancho'            => '0.50 ',
        'largo'            => '0.70 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'FUPE30 cmX05ESGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'FUNDAS ',
        'caracteristicas'            => 'PEDIATRICA ',
        'ancho'            => '0.30 ',
        'largo'            => '0.50 ',
        'color'            => 'ESTAMPADO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'INHE045X14BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'INMOVILIZADORES ',
        'caracteristicas'            => 'HERIDA ABIERTA ',
        'ancho'            => '0.45 ',
        'largo'            => '1.40 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'INLI06X24BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'INMOVILIZADORES ',
        'caracteristicas'            => 'LISO ',
        'ancho'            => '0.60 ',
        'largo'            => '2.40 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'INMA015X025BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'INMOVILIZADORES ',
        'caracteristicas'            => 'MANOS ',
        'ancho'            => '0.15 ',
        'largo'            => '0.25 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'INPE07X045ESGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'INMOVILIZADORES ',
        'caracteristicas'            => 'PEDIATRICO ',
        'ancho'            => '0.70 ',
        'largo'            => '0.45 ',
        'color'            => 'ESTAMPADO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'INTO045X14BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'INMOVILIZADORES ',
        'caracteristicas'            => 'TORAX ',
        'ancho'            => '0.45 ',
        'largo'            => '1.40 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'LOGR15X2BEDR ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'LONAS ',
        'caracteristicas'            => 'GRANDE ',
        'ancho'            => '1.50 ',
        'largo'            => '2.00 ',
        'color'            => 'BEIGE ',
        'tela'            => 'DRILAN ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'LOPE1X1BEDR ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'LONAS ',
        'caracteristicas'            => 'PEQUEÑA ',
        'ancho'            => '1.00 ',
        'largo'            => '1.00 ',
        'color'            => 'BEIGE ',
        'tela'            => 'DRILAN ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'PEGR075X13GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'PETOS ',
        'caracteristicas'            => 'GRANDES ',
        'ancho'            => '0.75 ',
        'largo'            => '1.30 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'PEME075X12GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'PETOS ',
        'caracteristicas'            => 'MEDIANOS ',
        'ancho'            => '0.75 ',
        'largo'            => '1.20 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SACA155X235BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'CAMA RESORTADA ',
        'ancho'            => '1.55 ',
        'largo'            => '2.35 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SACA105X225BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'CAMILLA RESORTADA ',
        'ancho'            => '1.05 ',
        'largo'            => '2.25 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SACA155X235GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'CAMA PLASTICA ',
        'ancho'            => '1.55 ',
        'largo'            => '2.35 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SACA15X225GRPL ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'CAMILLA PLASTICA ',
        'ancho'            => '1.50 ',
        'largo'            => '2.25 ',
        'color'            => 'GRIS ',
        'tela'            => 'PLASTITEX ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SACU1X17ESGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'CUNA ',
        'ancho'            => '1.00 ',
        'largo'            => '1.70 ',
        'color'            => 'ESTAMPADO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SALI1X17ESGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'LISA ',
        'ancho'            => '1.00 ',
        'largo'            => '1.70 ',
        'color'            => 'ESTAMPADO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SAMO25X125BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'MOVIMIENTO ',
        'ancho'            => '2.50 ',
        'largo'            => '1.25 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SAMO15X1ESGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'MOVIMIENTO PEDIATRICA ',
        'ancho'            => '1.50 ',
        'largo'            => '1.00 ',
        'color'            => 'ESTAMPADO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SAPE1X17ESGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'PEDIATRICA ',
        'ancho'            => '1.00 ',
        'largo'            => '1.70 ',
        'color'            => 'ESTAMPADO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SARE1X17BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'RESORTADA ',
        'ancho'            => '1.00 ',
        'largo'            => '1.70 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'SASO15X22BLGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'SABANAS ',
        'caracteristicas'            => 'SOBRE SABANA ',
        'ancho'            => '1.50 ',
        'largo'            => '2.20 ',
        'color'            => 'BLANCO ',
        'tela'            => 'GENERO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'TAGR12X07BEDR ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'TALEGOS ',
        'caracteristicas'            => 'GRANDE ',
        'ancho'            => '1.20 ',
        'largo'            => '0.70 ',
        'color'            => 'BEIGE ',
        'tela'            => 'DRILAN ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'TAME1X06BEDR ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'TALEGOS ',
        'caracteristicas'            => 'MEDIANO ',
        'ancho'            => '1.00 ',
        'largo'            => '0.60 ',
        'color'            => 'BEIGE ',
        'tela'            => 'DRILAN ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'TAPE08X05BEDR ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'TALEGOS ',
        'caracteristicas'            => 'PEQUEÑO ',
        'ancho'            => '0.80 ',
        'largo'            => '0.50 ',
        'color'            => 'BEIGE ',
        'tela'            => 'DRILAN ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'TOGR07X1BLTE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'TOALLAS ',
        'caracteristicas'            => 'GRANDE ',
        'ancho'            => '0.70 ',
        'largo'            => '1.00 ',
        'color'            => 'BLANCO ',
        'tela'            => 'TELA TOALLA ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'TOME05X05BLTE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'TOALLAS ',
        'caracteristicas'            => 'MEDIANA ',
        'ancho'            => '0.50 ',
        'largo'            => '0.50 ',
        'color'            => 'BLANCO ',
        'tela'            => 'TELA TOALLA ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'TOTO6X18VATO ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'TOLDILLOS ',
        'caracteristicas'            => 'TOLDILLOS ',
        'ancho'            => '6.00 ',
        'largo'            => '1.80 ',
        'color'            => 'VARIADO ',
        'tela'            => 'TOLDILLO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'UNTAS0X0VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'UNIFORMES ',
        'caracteristicas'            => 'TALLA S ',
        'ancho'            => '0.00 ',
        'largo'            => '0.00 ',
        'color'            => 'VERDE O AZUL ',
        'tela'            => 'GENERO O ANTIFLUIDO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'UNTAM0X0VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'UNIFORMES ',
        'caracteristicas'            => 'TALLA M ',
        'ancho'            => '0.00 ',
        'largo'            => '0.00 ',
        'color'            => 'VERDE O AZUL ',
        'tela'            => 'GENERO O ANTIFLUIDO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'UNTAL0X0VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'UNIFORMES ',
        'caracteristicas'            => 'TALLA L ',
        'ancho'            => '0.00 ',
        'largo'            => '0.00 ',
        'color'            => 'VERDE O AZUL ',
        'tela'            => 'GENERO O ANTIFLUIDO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'UNTAXL0X0VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'UNIFORMES ',
        'caracteristicas'            => 'TALLA XL ',
        'ancho'            => '0.00 ',
        'largo'            => '0.00 ',
        'color'            => 'VERDE O AZUL ',
        'tela'            => 'GENERO O ANTIFLUIDO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('compras')->insert([
        'serial'            => 'UNTAXXL0X0VEGE ',
        'estado_id'            => '1 ',
        'estado_ubi'            => 'Bodega ',
        'unidades'            => '100 ',
        'uni'            => '100 ',
        'elemento'            => 'UNIFORMES ',
        'caracteristicas'            => 'TALLA XXL ',
        'ancho'            => '0.00 ',
        'largo'            => '0.00 ',
        'color'            => 'VERDE O AZUL ',
        'tela'            => 'GENERO O ANTIFLUIDO ',
        'status'            => '1 ',
        'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at'        => Carbon::now()->format('Y-m-d H:i:s'),
        ]);


    }
}
